### ISSUE TITLE
the new pod sdk has include error

### ISSUE THREAD

**Issue by KevinTao511** [easemob/sdk-ios-cocoapods#10]
环信的工程师们，
帮我们看看，我们用老的库没有问题，现在用新的pod会有include error，是不是你们新的pod文件出问题了啊？
podfile：
pod 'EaseMobSDK', //:git => 'https://github.com/easemob/sdk-ios-cocoapods.git'

我们在prefix里面是这样import的：
# import <EaseMobSDK/EaseMob.h>

在线等！
感谢！

**Comment by lizilong1989** [comment]
@KevinTao511 应该没有问题, 现在SDK已经传到cocoadpos上了, 不需要后面指定github地址了, pod 'EaseMobSDK'即可
