### ISSUE TITLE
编译警告

### ISSUE THREAD

**Issue by shannonchou** [easemob/sdk-ios-cocoapods#11]
ld: warning: ignoring file /Users/shannon/Documents/xcodeworkspace/jiecao-ios/Pods/EaseMobSDK/EaseMobSDK/lib/libEaseMobClientSDKLite_arm64.a, file was built for archive which is not the architecture being linked (x86_64): /Users/shannon/Documents/xcodeworkspace/jiecao-ios/Pods/EaseMobSDK/EaseMobSDK/lib/libEaseMobClientSDKLite_arm64.a
ld: warning: ignoring file /Users/shannon/Documents/xcodeworkspace/jiecao-ios/Pods/EaseMobSDK/EaseMobSDK/lib/libEaseMobClientSDKLite_armv7.a, file was built for archive which is not the architecture being linked (x86_64): /Users/shannon/Documents/xcodeworkspace/jiecao-ios/Pods/EaseMobSDK/EaseMobSDK/lib/libEaseMobClientSDKLite_armv7.a
ld: warning: ignoring file /Users/shannon/Documents/xcodeworkspace/jiecao-ios/Pods/EaseMobSDK/EaseMobSDK/lib/libEaseMobClientSDKLite_armv7s.a, file was built for archive which is not the architecture being linked (x86_64): /Users/shannon/Documents/xcodeworkspace/jiecao-ios/Pods/EaseMobSDK/EaseMobSDK/lib/libEaseMobClientSDKLite_armv7s.a
ld: warning: ignoring file /Users/shannon/Documents/xcodeworkspace/jiecao-ios/Pods/EaseMobSDK/EaseMobSDK/lib/libEaseMobClientSDKLite_i386.a, file was built for archive which is not the architecture being linked (x86_64): /Users/shannon/Documents/xcodeworkspace/jiecao-ios/Pods/EaseMobSDK/EaseMobSDK/lib/libEaseMobClientSDKLite_i386.a

**Comment by lizilong1989** [comment]
@shannonchou 由于把sdk拆成不同平台导致的,现在已经合并了一个了
