### ISSUE TITLE
怎么有实时语音callManager相关的代码

### ISSUE THREAD

**Issue by zixun** [easemob/sdk-ios-cocoapods#14]
怎么有实时语音callManager相关的代码

**Comment by dujiepeng** [comment]
pod 'EaseMobSDKFull', :git => 'https://github.com/easemob/sdk-ios-cocoapods-integration.git'

**Comment by zixun** [comment]
@dujiepeng  我是说这个库里怎么有实时语音callManager相关的代码，这个不是没有实时语音的版本么
