### ISSUE TITLE
拜托，你们官网上SDK都更新到2.2.1了，这里还是2.1.9，这是什么情况，这里不重视更新么？？

### ISSUE THREAD

**Issue by Jsonmess** [easemob/sdk-ios-cocoapods#15]

**Comment by dujiepeng** [comment]
pod 'EaseMobSDK', :git => 'https://github.com/easemob/sdk-ios-cocoapods.git'

**Comment by Jsonmess** [comment]
OK,I will try

**Comment by huipengo** [comment]
pod 'EaseMobSDK', :git => 'https://github.com/easemob/sdk-ios-cocoapods.git'
