### ISSUE TITLE
pod安装后，一调用就报错

### ISSUE THREAD

**Issue by sophiaWang611** [easemob/sdk-ios-cocoapods#19]
pod安装，一调用就报错：

reason: '**\* -[NSBundle initWithURL:]: nil URL argument'
**\* First throw call stack:
(
    0   CoreFoundation                      0x000000010661fe65 **exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x00000001058c5deb objc_exception_throw + 48
    2   CoreFoundation                      0x000000010661fd9d +[NSException raise:format:] + 205
    3   Foundation                          0x000000010336977b -[NSBundle initWithURL:] + 87
    4   Foundation                          0x000000010336982a +[NSBundle bundleWithURL:] + 45
    5   ËßÖÈ£ü-ÂÆ∂Âé®                       0x0000000101b95c06 -[EMSDKConfigModel sdkBundle] + 141
    6   ËßÖÈ£ü-ÂÆ∂Âé®                       0x0000000101b95d08 -[EMSDKConfigModel initSDKConfigInfo] + 196
    7   ËßÖÈ£ü-ÂÆ∂Âé®                       0x0000000101b95a46 -[EMSDKConfigModel init] + 79
    8   ËßÖÈ£ü-ÂÆ∂Âé®                       0x0000000101b95b5f __34+[EMSDKConfigModel shareSDKConfig]_block_invoke + 41
    9   libdispatch.dylib                   0x0000000107ed149b _dispatch_client_callout + 8
    10  libdispatch.dylib                   0x0000000107ebce28 dispatch_once_f + 543
    11  ËßÖÈ£ü-ÂÆ∂Âé®                       0x0000000101b95b34 +[EMSDKConfigModel shareSDKConfig] + 46
    12  ËßÖÈ£ü-ÂÆ∂Âé®                       0x0000000101addaf2 -[EaseMob registerSDKWithAppKey:apnsCertName:otherConfig:] + 462
    13  ËßÖÈ£ü-ÂÆ∂Âé®                       0x0000000101add8fe -[EaseMob registerSDKWithAppKey:apnsCertName:] + 53
    14  ËßÖÈ£ü-ÂÆ∂Âé®                       0x0000000101a36901 -[AppDelegate(EaseMob) easemobApplication:didFinishLaunchingWithOptions:] + 209
    15  ËßÖÈ£ü-ÂÆ∂Âé®                       0x00000001019b2029 -[AppDelegate application:didFinishLaunchingWithOptions:] + 297
    16  UIKit                               0x00000001040971f1 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 272
    17  UIKit                               0x0000000104098397 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 3415
    18  UIKit                               0x000000010409ecc6 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1760
    19  UIKit                               0x000000010409be7b -[UIApplication workspaceDidEndTransaction:] + 188
    20  FrontBoardServices                  0x00000001096c7754 -[FBSSerialQueue _performNext] + 192
    21  FrontBoardServices                  0x00000001096c7ac2 -[FBSSerialQueue _performNextFromRunLoopSource] + 45
    22  CoreFoundation                      0x000000010654ba31 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION** + 17
    23  CoreFoundation                      0x000000010654195c __CFRunLoopDoSources0 + 556
    24  CoreFoundation                      0x0000000106540e13 __CFRunLoopRun + 867
    25  CoreFoundation                      0x0000000106540828 CFRunLoopRunSpecific + 488
    26  UIKit                               0x000000010409b7cd -[UIApplication _run] + 402
    27  UIKit                               0x00000001040a0610 UIApplicationMain + 171
    28  ËßÖÈ£ü-ÂÆ∂Âé®                       0x000000010199afbf main + 111
    29  libdyld.dylib                       0x0000000107f0592d start + 1
)

**Comment by dujiepeng** [comment]
podfile 如何写的，发下，谢谢。
