### ISSUE TITLE
EMFMDatabaseQueue.m line 147 -[EMFMDatabaseQueue inDatabase:]

### ISSUE THREAD

**Issue by cacawai** [easemob/sdk-ios-cocoapods#25]
Fabric 抓到的Crash，Crash率大概在0.3%左右，请看下是什么问题，SDK版本是2.1.9

Thread : Crashed: com.apple.root.default-qos
0  libdispatch.dylib              0x19834295c dispatch_sync + 34
1  XXXX                       0x10036c228 -[EMFMDatabaseQueue inDatabase:](EMFMDatabaseQueue.m:147)
2  XXXX                       0x1003ca11c -[DXDBManager createTables](DXDBManager.m:334)
3  XXXX                       0x1003cafec +[DXDBManager openEasemobDatabaseWithAccount:](DXDBManager.m:542)
4  XXXX                       0x10026ad38 -[EMChatManager(Login) loadDataFromDatabase](EMChatManager+Login.m:233)
5  XXXX                       0x100851f04 -[IMManagerViaEaseMob initalizeChat] + 3942132
6  XXXX                       0x1008527ac __64-[IMManagerViaEaseMob loginWithUsername:password:callbackBlock:]_block_invoke + 3944348
7  libdispatch.dylib              0x1983417b0 _dispatch_call_block_and_release + 24
8  libdispatch.dylib              0x198341770 _dispatch_client_callout + 16
9  libdispatch.dylib              0x19834fbb0 _dispatch_root_queue_drain + 2140
10 libdispatch.dylib              0x19834f34c _dispatch_worker_thread3 + 112
11 libsystem_pthread.dylib        0x198555478 _pthread_wqthread + 1092
12 libsystem_pthread.dylib        0x198555028 start_wqthread + 4

**Comment by lizilong1989** [comment]
@cacawai 新版本还有这个问题吗?
